TRAINING_COLUMNS = [
    'SeniorCitizen',
    'tenure',
    'MonthlyCharges',
    'TotalCharges',
    'gender_Female',
    'gender_Male',
    'InternetService_DSL',
    'InternetService_Fiber optic',
    'InternetService_No',
    'PaymentMethod_Bank transfer (automatic)',
    'PaymentMethod_Credit card (automatic)',
    'PaymentMethod_Electronic check',
    'PaymentMethod_Mailed check',
    'Partner_No',
    'Partner_Yes',
    'Dependents_No',
    'Dependents_Yes',
    'PhoneService_No',
    'PhoneService_Yes',
    'PaperlessBilling_No',
    'PaperlessBilling_Yes',
    'MultipleLines_No',
    'MultipleLines_Yes',
    'OnlineSecurity_No',
    'OnlineSecurity_Yes',
    'OnlineBackup_No',
    'OnlineBackup_Yes',
    'DeviceProtection_No',
    'DeviceProtection_Yes',
    'TechSupport_No',
    'TechSupport_Yes',
    'StreamingTV_No',
    'StreamingTV_Yes',
    'StreamingMovies_No',
    'StreamingMovies_Yes',
    'tenure_range',
    'Contract_Month-to-month',
    'Contract_One year',
    'Contract_Two year'
]